/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.5.1/samples
 */

plugins {
  kotlin("jvm") version "1.7.20"
}

repositories {
  mavenCentral()
}

dependencies {
  implementation("org.jetbrains.kotlin:kotlin-reflect:1.7.20")
}

tasks.withType<Jar> {
  archiveClassifier.set("uber")

  manifest {
    attributes["Main-Class"] = "com.github.htgazurex1212.adventofcode.MainKt"
  }

  from(sourceSets.main.get().output)

  dependsOn(configurations.runtimeClasspath)
  from({
    configurations.runtimeClasspath.get().filter { it.name.endsWith("jar") }.map { zipTree(it) }
  })

  duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
